### ISSUE TITLE
media queries 

### ISSUE THREAD

**Issue by EthanKubistek** [jpochetedmead/jpochetedmead.github.io#4]
media queries are commented out.
/**** SMALL ****/
/*
@media screen and (max-width: 768px) {
}
/**** MEDIUM ****/
/*
@media screen and (min-width: 768px) and (max-width: 1024px) {
}
/**** LARGE ****/
/*
@media screen and (min-width: 1024px) and (max-width: 1366px) {
}
/**** EXTRA LARGE ****/
/*
@media screen and (min-width: 1366px) {
}
© 2019 GitHub, Inc.

**Comment by jpochetedmead** [comment]
I'll fix it. Thank you!
